version: "3.3"
services:
  backend:
    container_name: inside-demo
    build:

    image: python
    hostname: backend
    ports:
      - "8080:8080"
  frontend:
    container_name: inside-db
    image: postgres:14.1
    environment:
      - BACKEND_HOSTNAME=backend
      - BACKEND_PORT=8080
      - POSTGRES_DB=demo
    volumes:

    ports:
      - "127.0.0.1:5432:5432"
